import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Link from "next/link";
import Hamburger from "@/components/Hamburger";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <nav className="w-full h-10 text-xl text-white bg-[#B0A695] flex items-center ">
          <Link className="mr-auto ml-5" href="/">
            GymRoo
          </Link>
          <div className="hidden md:flex w-2/3 lg:flex lg:w-1/2 items-center justify-evenly">
            <Link href="/products">Products</Link>
            <Link href="/cart">Cart</Link>
            <Link href="/about">About Us</Link>
            <Link href="/login">Sign In</Link>
          </div>
          <Hamburger />
        </nav>
        {children}
       
      </body>
    </html>
  );
}
